 default: &default
   adapter: postgresql
   encoding: unicode
   pool: 5
   host: localhost
   username: raboy1997
   password: vfrc1997

 development:
   <<: *default
   database: post_twitter_development



 test:
   <<: *default
   database: post_twitter_test


 production:
   <<: *default
   database: post_twitter_production
   username: raboy1997
   password: vfrc1997